<?php

/**
 * @file
 * Install/Uninstall Procedures of the watchlist module
 */

/**
 * Implements hook_uninstall().
 */
function watchlist_uninstall() {
  // TODO Please review the conversion of this statement to the D7 database API syntax.
  /* db_query("DELETE FROM {variable} WHERE name LIKE 'watchlist_%'") */
  db_delete('variable')
  ->condition('name', 'watchlist_%', 'LIKE')
  ->execute();
}
